SET(CPACK_PACKAGE_NAME "tmp_rk2")
SET(CPACK_PACKAGE_DESCRIPTION "Release VisitorApp")
SET(CPACK_PACKAGE_VENDOR "BMSTU")
SET(CPACK_PACKAGE_VERSION "0.1.6")

SET(CPACK_GENERATORS "TGZ;DEB")
SET(CPACK_COMPONENTS_ALL "visitor_lib;main")

#  Source package
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES
    "/.git/;"
    "/build/;"
    "/third-party/;"
    "/tests/;"
)

# DEB package
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "CoF-Luke")
SET(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
SET(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.31), libstdc++6 (>= 11), libm6, libgcc-s1")